#ifndef AOFLAGGER_VERSION_H
#define AOFLAGGER_VERSION_H

#define AOFLAGGER_VERSION_STR      "2.6.1"
#define AOFLAGGER_VERSION_MAJOR    2
#define AOFLAGGER_VERSION_MINOR    6
#define AOFLAGGER_VERSION_SUBMINOR 1
#define AOFLAGGER_VERSION_DATE_STR "2014-11-25"

#endif
