#ifndef AOFLAGGER_VERSION_H
#define AOFLAGGER_VERSION_H

#define AOFLAGGER_VERSION_STR      "2.7.1"
#define AOFLAGGER_VERSION_MAJOR    2
#define AOFLAGGER_VERSION_MINOR    7
#define AOFLAGGER_VERSION_SUBMINOR 1
#define AOFLAGGER_VERSION_DATE_STR "2015-07-01"

#endif
