#ifndef AOFLAGGER_VERSION_H
#define AOFLAGGER_VERSION_H

#define AOFLAGGER_VERSION_STR      "2.7.3"
#define AOFLAGGER_VERSION_MAJOR    2
#define AOFLAGGER_VERSION_MINOR    7
#define AOFLAGGER_VERSION_SUBMINOR 3
#define AOFLAGGER_VERSION_DATE_STR "2016-02-24"

#endif
